/* Generated by esbuild. Source is included in publish/src/. */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// publish/src/constance-account.ts
var constance_account_exports = {};
__export(constance_account_exports, {
  CONSTANCE_ACCOUNT_BASE_URL: () => CONSTANCE_ACCOUNT_BASE_URL,
  addBillingAccountSettings: () => addBillingAccountSettings,
  claimAccountFreeUsage: () => claimAccountFreeUsage,
  refreshBillingAccessToken: () => refreshBillingAccessToken,
  signInBillingAccount: () => signInBillingAccount,
  spendAccountCredits: () => spendAccountCredits,
  validateBillingSession: () => validateBillingSession
});
function errorDetail(response, fallback) {
  var _a, _b;
  return String(((_a = response.json) == null ? void 0 : _a.detail) || ((_b = response.json) == null ? void 0 : _b.message) || response.text || fallback);
}
async function authenticate(mode, email, password, installationId) {
  var _a, _b;
  const body = mode === "register" ? { email, password, external_customer_id: installationId } : { email, password };
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/${mode}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Billing ${mode} failed (HTTP ${response.status})`));
  }
  const accessToken = String(((_a = response.json) == null ? void 0 : _a.access_token) || "");
  const refreshToken = String(((_b = response.json) == null ? void 0 : _b.refresh_token) || "");
  if (!accessToken || !refreshToken) throw new Error("Constance did not return a complete billing session.");
  return { accessToken, refreshToken };
}
async function refreshBillingAccessToken(state) {
  var _a, _b;
  if (!state.billingRefreshToken) return false;
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/refresh`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ refresh_token: state.billingRefreshToken }),
      throw: false
    });
    if (response.status < 200 || response.status >= 300) return false;
    const accessToken = String(((_a = response.json) == null ? void 0 : _a.access_token) || "");
    const refreshToken = String(((_b = response.json) == null ? void 0 : _b.refresh_token) || "");
    if (!accessToken || !refreshToken) return false;
    state.billingAccessToken = accessToken;
    state.billingRefreshToken = refreshToken;
    return true;
  } catch (e) {
    return false;
  }
}
async function linkInstallation(adapter, token) {
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/installations/link`,
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      app_id: adapter.appId,
      installation_id: adapter.installationId,
      legacy_external_customer_id: adapter.installationId,
      platform: "obsidian",
      app_version: adapter.appVersion || void 0
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Installation link failed (HTTP ${response.status})`));
  }
}
async function signInBillingAccount(adapter, password, mode) {
  const email = adapter.state.billingEmail.trim().toLowerCase();
  if (!email || !email.includes("@")) throw new Error("Enter a valid billing email.");
  if (password.length < 8) throw new Error("Password must contain at least 8 characters.");
  if (!adapter.installationId) throw new Error("The plugin installation ID is not ready.");
  const session = await authenticate(mode, email, password, adapter.installationId);
  await linkInstallation(adapter, session.accessToken);
  adapter.state.billingEmail = email;
  adapter.state.billingAccessToken = session.accessToken;
  adapter.state.billingRefreshToken = session.refreshToken;
  adapter.state.billingAccountLinked = true;
  await adapter.persist();
  await adapter.syncBalance();
}
async function validateBillingSession(adapter) {
  const token = adapter.state.billingAccessToken;
  if (!token || !adapter.state.billingAccountLinked || !adapter.installationId) return false;
  const query = new URLSearchParams({ app_id: adapter.appId, installation_id: adapter.installationId });
  let response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/entitlements/me?${query.toString()}`,
    method: "GET",
    headers: { Authorization: `Bearer ${token}` },
    throw: false
  });
  if ((response.status === 401 || response.status === 403) && await refreshBillingAccessToken(adapter.state)) {
    await adapter.persist();
    response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/entitlements/me?${query.toString()}`,
      method: "GET",
      headers: { Authorization: `Bearer ${adapter.state.billingAccessToken}` },
      throw: false
    });
  }
  if (response.status === 401 || response.status === 403 || response.status === 404) {
    adapter.state.billingAccountLinked = false;
    adapter.state.billingAccessToken = "";
    adapter.state.billingRefreshToken = "";
    await adapter.persist();
    return false;
  }
  return response.status >= 200 && response.status < 300;
}
async function claimAccountFreeUsage(state, appId, installationId, eventId2, amount) {
  var _a, _b;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    let response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/free-usage/claim`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId2, amount }),
      throw: false
    });
    if ((response.status === 401 || response.status === 403) && await refreshBillingAccessToken(state)) {
      response = await (0, import_obsidian.requestUrl)({
        url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/free-usage/claim`,
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
        body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId2, amount }),
        throw: false
      });
    }
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    return { kind: "ok", remaining: Math.max(0, Number((_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.remaining) || 0) };
  } catch (error) {
    console.error("Constance account free-usage claim failed", error);
    return { kind: "error" };
  }
}
async function spendAccountCredits(state, appId, installationId, eventId2, amount) {
  var _a, _b, _c;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    let response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/credits/spend`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId2, amount }),
      throw: false
    });
    if ((response.status === 401 || response.status === 403) && await refreshBillingAccessToken(state)) {
      response = await (0, import_obsidian.requestUrl)({
        url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/credits/spend`,
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
        body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId2, amount }),
        throw: false
      });
    }
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    const balance = Number((_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance);
    return Number.isFinite(balance) ? { kind: "ok", balance: Math.max(0, balance) } : { kind: "error" };
  } catch (error) {
    console.error("Constance authenticated credit spend failed", error);
    return { kind: "error" };
  }
}
function addBillingAccountSettings(containerEl, adapter) {
  let password = "";
  new import_obsidian.Setting(containerEl).setName("Billing account email").setDesc("Used for sign-in, purchase restore, and checkout. Reinstalling no longer creates a new free allowance.").addText((text) => text.setPlaceholder("you@example.com").setValue(adapter.state.billingEmail).onChange(async (value) => {
    adapter.state.billingEmail = value.trim();
    await adapter.persist();
  }));
  new import_obsidian.Setting(containerEl).setName("Billing account password").setDesc("Used only for this sign-in request. The password is never saved by the plugin.").addText((text) => {
    text.inputEl.type = "password";
    text.setPlaceholder("At least 8 characters").onChange((value) => {
      password = value;
    });
  });
  const status = adapter.state.billingAccountLinked ? "Signed in and linked" : "Not signed in";
  new import_obsidian.Setting(containerEl).setName("Billing account").setDesc(`${status}. The saved bearer session can restore purchases; your password is not stored.`).addButton((button) => button.setButtonText("Sign in").onClick(async () => {
    var _a;
    button.setDisabled(true);
    try {
      await signInBillingAccount(adapter, password, "login");
      new import_obsidian.Notice("Billing account signed in and this installation was linked.");
      (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
    } catch (error) {
      new import_obsidian.Notice(error instanceof Error ? error.message : "Billing sign-in failed.");
    } finally {
      button.setDisabled(false);
    }
  })).addButton((button) => button.setButtonText("Create account").onClick(async () => {
    var _a;
    button.setDisabled(true);
    try {
      await signInBillingAccount(adapter, password, "register");
      new import_obsidian.Notice("Billing account created and this installation was linked.");
      (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
    } catch (error) {
      new import_obsidian.Notice(error instanceof Error ? error.message : "Billing account creation failed.");
    } finally {
      button.setDisabled(false);
    }
  })).addButton((button) => button.setButtonText("Sign out").setDisabled(!adapter.state.billingAccessToken).onClick(async () => {
    var _a;
    adapter.state.billingAccessToken = "";
    adapter.state.billingRefreshToken = "";
    adapter.state.billingAccountLinked = false;
    await adapter.persist();
    new import_obsidian.Notice("Billing account signed out on this installation.");
    (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
  }));
}
var import_obsidian, CONSTANCE_ACCOUNT_BASE_URL;
var init_constance_account = __esm({
  "publish/src/constance-account.ts"() {
    "use strict";
    import_obsidian = require("obsidian");
    CONSTANCE_ACCOUNT_BASE_URL = "https://app.tutivsoft.com";
  }
});

// publish/src/main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_CAIRN: () => VIEW_TYPE_CAIRN,
  default: () => CairnVaultLinterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// publish/src/core.ts
var EXTERNAL_TARGET = /^(?:[a-z][a-z\d+.-]*:|\/\/)/i;
var SAFE_TARGET = /^[^\u0000-\u001f<>|]+$/;
function normalizePath(path) {
  const parts = [];
  path.replace(/\\/g, "/").replace(/^\/+/, "").split("/").forEach((part) => {
    if (!part || part === ".") return;
    if (part === "..") {
      parts.pop();
      return;
    }
    parts.push(part);
  });
  return parts.join("/").replace(/\/$/, "").toLowerCase();
}
function normalizeText(value) {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}
function slugifyHeading(value) {
  return normalizeText(value).replace(/[?.,:;!()[\]{}'"`]/g, "").replace(/\s+/g, "-");
}
function fileSignature(file) {
  return `${file.mtime}:${file.size}`;
}
function splitLines(content) {
  return content.split(/\r?\n/);
}
function currentSection(lines, lineIndex) {
  for (let i = lineIndex; i >= 0; i--) {
    const match = /^(#{1,6})\s+(.+?)\s*$/.exec(lines[i]);
    if (match) return match[2].replace(/\s+#+\s*$/, "").trim();
  }
  return "(document)";
}
function parseAliases(content) {
  const frontmatter = /^(?:---|\+\+\+)\r?\n([\s\S]*?)\r?\n(?:---|\+\+\+)\r?\n/.exec(content);
  if (!frontmatter) return [];
  const aliases = [];
  const lines = frontmatter[1].split(/\r?\n/);
  for (const line of lines) {
    const match = /^\s*(?:aliases?|alias)\s*:\s*(.*)$/i.exec(line);
    if (!match) continue;
    const value = match[1].trim();
    if (value.startsWith("[")) {
      aliases.push(...value.slice(1, value.lastIndexOf("]")).split(",").map((item) => item.trim().replace(/^['"]|['"]$/g, "")).filter(Boolean));
    } else if (value) {
      aliases.push(value.replace(/^['"]|['"]$/g, ""));
    }
  }
  return aliases;
}
function parseHeadingsAndBlocks(content) {
  const lines = splitLines(content);
  const headings = [];
  const blocks = [];
  lines.forEach((line, index) => {
    const heading = /^(#{1,6})\s+(.+?)\s*$/.exec(line);
    if (heading) {
      const withoutId = heading[2].replace(/\s*\{#([^}]+)\}\s*$/, "").replace(/\s+#+\s*$/, "").trim();
      const custom = /\{#([^}]+)\}/.exec(heading[2]);
      headings.push({ text: withoutId, id: (custom == null ? void 0 : custom[1].trim().toLowerCase()) || slugifyHeading(withoutId), line: index + 1 });
    }
    const blockMatches = [...line.matchAll(/\^([A-Za-z0-9][A-Za-z0-9_-]*)\s*$/g)];
    blockMatches.forEach((match) => blocks.push({ id: match[1].toLowerCase(), line: index + 1 }));
  });
  return { headings, blocks };
}
function stripMarkdownDestination(raw) {
  let value = raw.trim();
  if (value.startsWith("<") && value.includes(">")) value = value.slice(1, value.indexOf(">"));
  const title = /^([^\s]+)\s+(?:["'].*["']|\(.*\))$/.exec(value);
  return (title == null ? void 0 : title[1]) || value;
}
function parseTarget(target) {
  let value = target.trim();
  let fragment = "";
  let fragmentKind = "none";
  const hash = value.indexOf("#");
  const caret = value.indexOf("^");
  if (hash >= 0 && (caret < 0 || hash < caret)) {
    fragment = value.slice(hash + 1).trim();
    value = value.slice(0, hash).trim();
    fragmentKind = "heading";
  } else if (caret >= 0) {
    fragment = value.slice(caret + 1).trim();
    value = value.slice(0, caret).trim();
    fragmentKind = "block";
  }
  return { path: value, fragment, fragmentKind };
}
function parseLinks(content) {
  var _a;
  const links = [];
  const lines = splitLines(content);
  const addLink = (link, offset) => {
    const line = content.slice(0, offset).split(/\r?\n/).length;
    links.push({ ...link, line, section: currentSection(lines, line - 1) });
  };
  const wiki = /(!?)\[\[([^\]\n]+)\]\]/g;
  for (const match of content.matchAll(wiki)) {
    const raw = match[0];
    const inner = match[2].trim();
    const parts = inner.split("|");
    const target = ((_a = parts.shift()) == null ? void 0 : _a.trim()) || "";
    const parsed = parseTarget(target);
    addLink({ kind: "wiki", embed: match[1] === "!", raw, target, display: parts.join("|").trim(), ...parsed, start: match.index || 0, end: (match.index || 0) + raw.length }, match.index || 0);
  }
  const markdown = /(!?)\[([^\]\n]*)\]\(([^)\n]*)\)/g;
  for (const match of content.matchAll(markdown)) {
    const raw = match[0];
    const target = stripMarkdownDestination(match[3]);
    const parsed = parseTarget(target);
    addLink({ kind: "markdown", embed: match[1] === "!", raw, target, display: match[2], ...parsed, start: match.index || 0, end: (match.index || 0) + raw.length }, match.index || 0);
  }
  return links.sort((a, b) => a.start - b.start);
}
function malformedLinkFinding(sourcePath, content, line, raw, explanation) {
  return makeFinding("malformed-link", "medium", sourcePath, line, "(document)", raw, explanation, false, surroundingText(content, line));
}
function surroundingText(content, line) {
  const lines = splitLines(content);
  return lines.slice(Math.max(0, line - 2), Math.min(lines.length, line + 1)).map((value, index) => `${Math.max(1, line - 1 + index)}: ${value}`).join("\n");
}
function makeFinding(type, severity, sourcePath, line, section, target, explanation, resolved, context = "") {
  const id = `${type}|${normalizePath(sourcePath)}|${line}|${normalizeText(target)}|${normalizeText(context)}`;
  return { id, type, severity, sourcePath, line, section, context, target, explanation, resolved };
}
function pathWithoutExtension(path) {
  return path.replace(/\.[^/.]+$/, "");
}
function matchesPattern(path, pattern) {
  const normalized = normalizePath(path);
  const p = normalizePath(pattern.trim());
  if (!p) return false;
  const regex = new RegExp(`^${p.split("*").map((part) => part.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join(".*")}$`, "i");
  return regex.test(normalized);
}
function isIgnoredPath(path, settings) {
  const normalized = normalizePath(path);
  const folders = settings.ignoredFolders.split(/\r?\n|,/).map((value) => normalizePath(value)).filter(Boolean);
  if (folders.some((folder) => normalized === folder || normalized.startsWith(`${folder}/`))) return true;
  return settings.ignoredPatterns.split(/\r?\n|,/).some((pattern) => matchesPattern(normalized, pattern));
}
function isHidden(path) {
  return normalizePath(path).split("/").some((part) => part.startsWith("."));
}
function resolveNote(path, source, byPath, byBasename, byAlias) {
  var _a, _b;
  const raw = path.trim().replace(/^\//, "");
  if (!raw) return byPath.get(normalizePath(source.path));
  const direct = byPath.get(normalizePath(raw)) || byPath.get(normalizePath(`${raw}.md`));
  if (direct) return direct;
  const relative = raw.startsWith("./") ? normalizePath(`${source.path.split("/").slice(0, -1).join("/")}/${raw.slice(2)}`) : "";
  if (relative) {
    const relativeNote = byPath.get(relative) || byPath.get(`${relative}.md`);
    if (relativeNote) return relativeNote;
  }
  return ((_a = byBasename.get(normalizeText(pathWithoutExtension(raw)))) == null ? void 0 : _a[0]) || ((_b = byAlias.get(normalizeText(raw))) == null ? void 0 : _b[0]);
}
function resolveAnyFile(path, source, files) {
  const raw = path.trim().replace(/^\//, "");
  if (!raw) return void 0;
  const direct = files.get(normalizePath(raw));
  if (direct) return direct;
  const relative = raw.startsWith("./") ? normalizePath(`${source.path.split("/").slice(0, -1).join("/")}/${raw.slice(2)}`) : "";
  return relative ? files.get(relative) : void 0;
}
function cleanMeaningfulText(content) {
  const withoutFrontmatter = content.replace(/^(?:---|\+\+\+)\r?\n[\s\S]*?\r?\n(?:---|\+\+\+)\r?\n/, "");
  const meaningful = withoutFrontmatter.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !/^<!--.*-->$/.test(line) && !/^#{1,6}\s*$/.test(line));
  return { text: meaningful.join(" ").replace(/[`*_>#\[\]{}]/g, "").trim(), lines: meaningful.length };
}
function attachRepair(finding, link, before, after) {
  finding.repair = { label: "Apply exact link repair", before, after, start: link.start, end: link.end };
}
function scanVault(reader, settings, scopePaths, incremental = false, signal, onProgress, previousFindings = []) {
  const started = Date.now();
  return (async () => {
    const allFiles = reader.getFiles().filter((file) => !isIgnoredPath(file.path, settings) && (settings.scanHiddenFiles || !isHidden(file.path)));
    const scanFiles = allFiles.filter((file) => settings.scanNonMarkdownFiles || file.extension.toLowerCase() === "md");
    const selected = (scopePaths == null ? void 0 : scopePaths.length) ? scanFiles.filter((file) => scopePaths.includes(file.path)) : scanFiles;
    const selectedPaths = new Set(selected.map((file) => file.path));
    const explicitScope = (scopePaths == null ? void 0 : scopePaths.length) ? new Set(scopePaths) : null;
    const errors = [];
    const signatures = {};
    allFiles.forEach((file) => signatures[file.path] = fileSignature(file));
    const noteFiles = allFiles.filter((file) => file.extension.toLowerCase() === "md");
    const byPath = /* @__PURE__ */ new Map();
    const byBasename = /* @__PURE__ */ new Map();
    const byAlias = /* @__PURE__ */ new Map();
    const changedOnly = incremental && Object.keys(settings.lastFileSignatures).length > 0;
    let scanned = 0;
    onProgress == null ? void 0 : onProgress({ phase: "indexing", currentPath: "", scanned: 0, total: selected.length, findings: 0 });
    const pathsRead = /* @__PURE__ */ new Set();
    for (const file of noteFiles) {
      if (signal == null ? void 0 : signal.aborted) return { findings: [], errors, filesScanned: scanned, durationMs: Date.now() - started, cancelled: true, signatures };
      const shouldRead = !changedOnly || (explicitScope == null ? void 0 : explicitScope.has(file.path)) === true || settings.lastFileSignatures[file.path] !== fileSignature(file);
      if (!shouldRead) continue;
      pathsRead.add(file.path);
      try {
        const content = await reader.read(file);
        const parsed = parseHeadingsAndBlocks(content);
        const index = { file: { ...file, content }, content, ...parsed, aliases: parseAliases(content), outgoing: parseLinks(content) };
        byPath.set(normalizePath(file.path), index);
        const basenameKey = normalizeText(pathWithoutExtension(file.basename || file.path.split("/").pop() || ""));
        byBasename.set(basenameKey, [...byBasename.get(basenameKey) || [], index]);
        index.aliases.forEach((alias) => byAlias.set(normalizeText(alias), [...byAlias.get(normalizeText(alias)) || [], index]));
        scanned++;
        onProgress == null ? void 0 : onProgress({ phase: "reading", currentPath: file.path, scanned, total: selected.length, findings: 0 });
      } catch (error) {
        errors.push({ path: file.path, message: error instanceof Error ? error.message : String(error) });
      }
      await Promise.resolve();
    }
    const readableFiles = new Map(allFiles.map((file) => [normalizePath(file.path), file]));
    const findings = changedOnly ? previousFindings.filter((finding) => !pathsRead.has(finding.sourcePath)) : [];
    const incoming = /* @__PURE__ */ new Map();
    byPath.forEach((note) => note.outgoing.forEach((link) => {
      const target = resolveNote(link.path, note.file, byPath, byBasename, byAlias);
      if (target) incoming.set(target.file.path, (incoming.get(target.file.path) || 0) + 1);
    }));
    const blockOccurrences = /* @__PURE__ */ new Map();
    const headingOccurrences = /* @__PURE__ */ new Map();
    byPath.forEach((note) => {
      note.blocks.forEach((block) => blockOccurrences.set(block.id, [...blockOccurrences.get(block.id) || [], { note, block }]));
      note.headings.forEach((heading) => {
        const key = `${normalizePath(note.file.path)}|${heading.id}`;
        headingOccurrences.set(key, [...headingOccurrences.get(key) || [], { note, heading }]);
      });
    });
    for (const [id, occurrences] of blockOccurrences) {
      if (occurrences.length < 2 || !settings.checks["duplicate-block-id"]) continue;
      occurrences.forEach(({ note, block }) => {
        if (!selectedPaths.has(note.file.path)) return;
        findings.push(makeFinding("duplicate-block-id", "high", note.file.path, block.line, currentSection(splitLines(note.content), block.line - 1), `^${id}`, `Block ID ^${id} is repeated ${occurrences.length} times in the vault and may resolve ambiguously.`, false));
      });
    }
    byPath.forEach((note) => {
      if (!selectedPaths.has(note.file.path)) return;
      if (settings.checks["duplicate-heading-id"]) {
        const seen = /* @__PURE__ */ new Map();
        note.headings.forEach((heading) => seen.set(heading.id, [...seen.get(heading.id) || [], heading]));
        seen.forEach((headings, id) => {
          if (headings.length < 2) return;
          headings.forEach((heading) => findings.push(makeFinding("duplicate-heading-id", "medium", note.file.path, heading.line, heading.text, `#${id}`, `Heading anchor #${id} is produced more than once in this note.`, false)));
        });
      }
      if (settings.checks["malformed-link"]) {
        splitLines(note.content).forEach((line, index) => {
          if (line.includes("[[") && !line.includes("]]")) findings.push(malformedLinkFinding(note.file.path, note.content, index + 1, line.trim(), "This wikilink is not closed before the end of the line."));
          if (line.includes("](") && !line.includes(")")) findings.push(malformedLinkFinding(note.file.path, note.content, index + 1, line.trim(), "This Markdown link is not closed before the end of the line."));
        });
      }
      const seenLinks = /* @__PURE__ */ new Map();
      note.outgoing.forEach((link) => {
        const malformed = !link.target || !SAFE_TARGET.test(link.target) || link.kind === "wiki" && /[\[\]]/.test(link.target);
        const context = surroundingText(note.content, link.line);
        if (malformed && settings.checks["malformed-link"]) findings.push(malformedLinkFinding(note.file.path, note.content, link.line, link.raw, "This link target contains unsupported or malformed characters and cannot be resolved safely."));
        if (EXTERNAL_TARGET.test(link.path)) return;
        const resolution = link.kind === "wiki" ? resolveNote(link.path, note.file, byPath, byBasename, byAlias) || (link.embed ? resolveAnyFile(link.path, note.file, readableFiles) : void 0) : !link.path && link.fragmentKind === "heading" ? byPath.get(normalizePath(note.file.path)) : resolveAnyFile(link.path, note.file, readableFiles);
        const targetNote = link.kind === "wiki" && resolution && "headings" in resolution ? resolution : void 0;
        if (!resolution) {
          if (link.embed && settings.checks["broken-embed"]) findings.push(makeFinding("broken-embed", "high", note.file.path, link.line, link.section, link.target, "This embedded note or local attachment does not exist in the vault.", false, context));
          else if (link.kind === "wiki" && /\s/.test(link.path) && settings.checks["missing-alias"]) findings.push(makeFinding("missing-alias", "medium", note.file.path, link.line, link.section, link.target, "No note exposes this text as an alias, and no matching note path was found.", false, context));
          else if (settings.checks[link.kind === "wiki" ? "broken-wikilink" : "broken-markdown-link"]) findings.push(makeFinding(link.kind === "wiki" ? "broken-wikilink" : "broken-markdown-link", "high", note.file.path, link.line, link.section, link.target, link.kind === "wiki" ? "The wikilink target does not resolve to a note." : "The Markdown link target does not resolve to a vault file.", false, context));
        } else if (link.fragmentKind !== "none") {
          const fragment = normalizeText(link.fragment);
          if (link.fragmentKind === "block") {
            const exists = targetNote == null ? void 0 : targetNote.blocks.some((block) => block.id === fragment);
            if (!exists && settings.checks["missing-block-id"]) findings.push(makeFinding("missing-block-id", "high", note.file.path, link.line, link.section, link.target, `Block ID ^${link.fragment} does not exist in the target note.`, false, context));
          } else {
            const exists = targetNote == null ? void 0 : targetNote.headings.some((heading) => heading.id === fragment || normalizeText(heading.text) === fragment);
            if (!exists && settings.checks["missing-heading"]) findings.push(makeFinding("missing-heading", "medium", note.file.path, link.line, link.section, link.target, `Heading #${link.fragment} does not exist in the target note.`, false, context));
          }
        }
        const resolvedPath = resolution ? "file" in resolution ? resolution.file.path : resolution.path : link.path;
        const canonical = `${resolvedPath}|${link.fragmentKind}|${normalizeText(link.fragment)}`;
        seenLinks.set(canonical, [...seenLinks.get(canonical) || [], link]);
        const duplicateGroup = seenLinks.get(canonical);
        if (duplicateGroup && duplicateGroup.length > 1 && settings.checks["duplicate-link"]) {
          const first = duplicateGroup[0];
          const duplicate = makeFinding("duplicate-link", "low", note.file.path, link.line, link.section, link.target, `This link repeats the same target already linked at line ${first.line}.`, true, context);
          attachRepair(duplicate, link, link.raw, "");
          findings.push(duplicate);
        }
      });
      if (settings.checks["empty-stub"]) {
        const clean = cleanMeaningfulText(note.content);
        const isStub = clean.text.length <= settings.emptyStubMaxCharacters && clean.lines <= settings.emptyStubMaxMeaningfulLines && (incoming.get(note.file.path) || 0) === 0 && note.outgoing.length === 0;
        if (isStub) findings.push(makeFinding("empty-stub", "low", note.file.path, 1, "(document)", note.file.path, "This Markdown note is empty or nearly empty and has no detected incoming or outgoing links.", false, clean.text || "(no meaningful text)"));
      }
      onProgress == null ? void 0 : onProgress({ phase: "checking", currentPath: note.file.path, scanned, total: selected.length, findings: findings.length });
    });
    const unique = /* @__PURE__ */ new Map();
    findings.forEach((finding) => unique.set(finding.id, finding));
    const resultFindings = [...unique.values()].sort((a, b) => a.sourcePath.localeCompare(b.sourcePath) || a.line - b.line || a.type.localeCompare(b.type));
    onProgress == null ? void 0 : onProgress({ phase: "complete", currentPath: "", scanned, total: selected.length, findings: resultFindings.length });
    return { findings: resultFindings, errors, filesScanned: scanned, durationMs: Date.now() - started, cancelled: false, signatures };
  })();
}
function applyIgnoredFindings(findings, ignored) {
  return findings.map((finding) => {
    const match = ignored.find((item) => item.scope === "finding" ? item.key === finding.id : item.scope === "source" ? item.key === finding.sourcePath : finding.sourcePath === item.key || finding.sourcePath.startsWith(`${item.key}/`));
    return match ? { ...finding, ignored: true, ignoredReason: match.reason } : finding;
  });
}
function findingCounts(findings) {
  return { total: findings.length, high: findings.filter((finding) => finding.severity === "high" && !finding.ignored).length, ignored: findings.filter((finding) => finding.ignored).length };
}

// publish/src/repair.ts
function applyTextRepairs(before, proposals) {
  let after = before;
  const applied = [];
  const skipped = [];
  [...proposals].sort((a, b) => b.start - a.start).forEach((proposal) => {
    if (after.slice(proposal.start, proposal.end) !== proposal.before) {
      skipped.push(proposal);
      return;
    }
    after = `${after.slice(0, proposal.start)}${proposal.after}${after.slice(proposal.end)}`;
    applied.push(proposal);
  });
  return { after, applied, skipped };
}
function canRollback(current, recordedAfter) {
  return current === recordedAfter;
}

// publish/src/journal.ts
async function prepareRepairJournal(adapter, path, content) {
  const existed = await adapter.exists(path);
  const previous = existed ? await adapter.read(path) : null;
  if (previous !== null) await adapter.write(`${path}.previous`, previous);
  const restore = async () => {
    if (previous !== null) await adapter.write(path, previous);
    else if (await adapter.exists(path)) await adapter.remove(path);
  };
  try {
    await adapter.write(path, content);
    if (await adapter.read(path) !== content) throw new Error("Repair journal verification failed");
  } catch (error) {
    await restore();
    throw error;
  }
  return restore;
}

// publish/src/billing.ts
async function claimAccountFreeUsage2(...args) {
  const module2 = await Promise.resolve().then(() => (init_constance_account(), constance_account_exports));
  return module2.claimAccountFreeUsage(...args);
}
var BASE_URL = "https://app.tutivsoft.com";
var CAIRN_APP_ID = "cairn-vault-linter";
var CAIRN_PLAN_CODES = {
  usd_001: "one_time",
  usd_010: "standard"
};
var CAIRN_PRICE_IDS = {
  usd_001: "pri_01m28hmgj33fkt4epnk2rvzgcw",
  // $1 -> 100 repair batches
  usd_010: "pri_01m28hmhe4ceh5g46ay287f0vc"
  // $10 -> 1,000 repair batches
};
var defaultRequester = async (request) => {
  const { requestUrl: requestUrl2 } = await import("obsidian");
  return requestUrl2(request);
};
function showNotice(message) {
  void import("obsidian").then(({ Notice: Notice4 }) => new Notice4(message)).catch(() => void 0);
}
async function requestWithFreshAccessToken(host, requester, buildRequest) {
  let response = await requester(buildRequest());
  if ((response.status === 401 || response.status === 403) && host.settings.billingRefreshToken) {
    const { refreshBillingAccessToken: refreshBillingAccessToken2 } = await Promise.resolve().then(() => (init_constance_account(), constance_account_exports));
    if (await refreshBillingAccessToken2(host.settings)) {
      await host.persistBillingSettings();
      response = await requester(buildRequest());
    }
  }
  return response;
}
function localDateKey(date = /* @__PURE__ */ new Date()) {
  const pad = (value) => String(value).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}
function generateSecureDeviceId(randomSource = window.crypto) {
  const bytes = new Uint8Array(16);
  randomSource.getRandomValues(bytes);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}
function isValidDeviceId(value) {
  return /^[a-f0-9]{32}$/i.test(value);
}
function ensureDeviceId(host) {
  if (!isValidDeviceId(host.settings.constanceDeviceId)) {
    host.settings.constanceDeviceId = generateSecureDeviceId();
    host.settings.purchasedRepairBatches = 0;
  }
  return host.settings.constanceDeviceId;
}
function resetDailyFreeRepairs(settings, date = /* @__PURE__ */ new Date()) {
  const today = localDateKey(date);
  if (settings.freeRepairDay !== today) {
    settings.freeRepairDay = today;
    settings.freeRepairBatchesUsed = 0;
  }
  const freeUsed = Number(settings.freeRepairBatchesUsed);
  const purchased = Number(settings.purchasedRepairBatches);
  settings.freeRepairBatchesUsed = Number.isFinite(freeUsed) ? Math.max(0, Math.min(3, Math.trunc(freeUsed))) : 0;
  settings.purchasedRepairBatches = Number.isFinite(purchased) ? Math.max(0, Math.trunc(purchased)) : 0;
}
function hasWritableRepairPlans(plans) {
  return plans.some((plan) => plan.before !== plan.after);
}
function eventId() {
  const bytes = new Uint8Array(12);
  window.crypto.getRandomValues(bytes);
  return `evt_${Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("")}`;
}
async function fetchBalance(host, requester = defaultRequester) {
  var _a, _b, _c;
  const deviceId = ensureDeviceId(host);
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) throw new Error("Billing account is not linked");
  const response = await requestWithFreshAccessToken(host, requester, () => ({
    url: `${BASE_URL}/api/v1/billing/entitlements/me?${new URLSearchParams({ app_id: CAIRN_APP_ID, installation_id: deviceId }).toString()}`,
    method: "GET",
    headers: { Authorization: `Bearer ${host.settings.billingAccessToken}` },
    throw: false
  }));
  if (response.status < 200 || response.status >= 300) throw new Error(`Entitlement sync failed: HTTP ${response.status}`);
  return Math.max(0, Number((_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance) || 0);
}
async function spendConstanceCredits(host, amount, requester = defaultRequester, stableEventId = eventId()) {
  var _a, _b, _c;
  if (!Number.isInteger(amount) || amount !== 1) return { kind: "error" };
  const deviceId = ensureDeviceId(host);
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) return { kind: "error" };
  try {
    const response = await requestWithFreshAccessToken(host, requester, () => ({
      url: `${BASE_URL}/api/v1/billing/credits/spend`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${host.settings.billingAccessToken}` },
      body: JSON.stringify({ app_id: CAIRN_APP_ID, installation_id: deviceId, amount, event_id: stableEventId }),
      throw: false
    }));
    if (response.status === 402 || response.status === 404) return { kind: "insufficient" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    return { kind: "ok", balance: Math.max(0, Number((_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance) || 0) };
  } catch (error) {
    console.warn("Cairn: Constance credit spend failed", error);
    return { kind: "error" };
  }
}
async function syncBalance(host, requester = defaultRequester) {
  const deviceId = ensureDeviceId(host);
  try {
    if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) return;
    host.settings.purchasedRepairBatches = await fetchBalance(host, requester);
    await host.persistBillingSettings();
  } catch (error) {
    console.warn("Cairn: Constance balance sync failed", error);
  }
}
async function initializeBilling(host) {
  var _a, _b, _c;
  ensureDeviceId(host);
  host.settings.pendingFreeUsageClaims = [...new Set(((_a = host.settings.pendingFreeUsageClaims) != null ? _a : []).filter((id) => typeof id === "string" && id.startsWith("free_")))];
  host.settings.pendingRepairCharges = [...new Set(((_b = host.settings.pendingRepairCharges) != null ? _b : []).filter((id) => typeof id === "string" && id.startsWith("evt_")))];
  host.settings.pendingCheckoutKeys = Object.fromEntries(Object.entries((_c = host.settings.pendingCheckoutKeys) != null ? _c : {}).filter(([pack, key]) => (pack === "usd_001" || pack === "usd_010") && typeof key === "string" && key.startsWith("checkout_")));
  resetDailyFreeRepairs(host.settings);
  await host.persistBillingSettings();
  void syncBalance(host).then(async () => {
    await retryPendingFreeUsageClaims(host);
    await retryPendingRepairCharges(host);
  });
}
async function retryPendingFreeUsageClaims(host) {
  var _a;
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) return;
  const pending = [...(_a = host.settings.pendingFreeUsageClaims) != null ? _a : []];
  for (const stableEventId of pending) {
    const result = await claimAccountFreeUsage2(host.settings, CAIRN_APP_ID, host.settings.constanceDeviceId, stableEventId, 1);
    if (result.kind === "error") break;
    host.settings.pendingFreeUsageClaims = host.settings.pendingFreeUsageClaims.filter((id) => id !== stableEventId);
    if (result.kind === "auth-required") {
      host.settings.billingAccessToken = "";
      host.settings.billingRefreshToken = "";
      host.settings.billingAccountLinked = false;
      await host.persistBillingSettings();
      break;
    }
    if (result.kind === "ok") {
      resetDailyFreeRepairs(host.settings);
      host.settings.freeRepairBatchesUsed = Math.max(0, 3 - result.remaining);
    }
    await host.persistBillingSettings();
  }
}
async function retryPendingRepairCharges(host, requester = defaultRequester) {
  var _a;
  const pending = [...(_a = host.settings.pendingRepairCharges) != null ? _a : []];
  for (const stableEventId of pending) {
    const result = await spendConstanceCredits(host, 1, requester, stableEventId);
    if (result.kind === "error") break;
    host.settings.pendingRepairCharges = host.settings.pendingRepairCharges.filter((id) => id !== stableEventId);
    host.settings.purchasedRepairBatches = result.kind === "insufficient" ? 0 : result.balance;
    await host.persistBillingSettings();
  }
}
async function reserveRepairBatch(host, requester = defaultRequester) {
  var _a, _b, _c;
  ensureDeviceId(host);
  resetDailyFreeRepairs(host.settings);
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) {
    showNotice("Cairn: sign in or create a billing account in plugin settings before applying repairs.");
    return null;
  }
  if (host.settings.freeRepairBatchesUsed < 3) {
    await retryPendingFreeUsageClaims(host);
    if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) {
      showNotice("Cairn: sign in or create a billing account before applying repairs.");
      return null;
    }
    if (((_a = host.settings.pendingFreeUsageClaims) != null ? _a : []).length) {
      showNotice("Cairn: the account allowance could not be verified.");
      return null;
    }
    const stableFreeEventId = `free_${eventId()}`;
    host.settings.pendingFreeUsageClaims = [...(_b = host.settings.pendingFreeUsageClaims) != null ? _b : [], stableFreeEventId];
    await host.persistBillingSettings();
    const accountFree = await claimAccountFreeUsage2(host.settings, CAIRN_APP_ID, host.settings.constanceDeviceId, stableFreeEventId, 1);
    if (accountFree.kind !== "ok") {
      if (accountFree.kind !== "error") host.settings.pendingFreeUsageClaims = host.settings.pendingFreeUsageClaims.filter((id) => id !== stableFreeEventId);
      if (accountFree.kind === "auth-required") {
        host.settings.billingAccessToken = "";
        host.settings.billingRefreshToken = "";
        host.settings.billingAccountLinked = false;
        await host.persistBillingSettings();
      } else if (accountFree.kind !== "error") await host.persistBillingSettings();
      showNotice(accountFree.kind === "insufficient" ? "Cairn: today's account free allowance is exhausted." : "Cairn: the account allowance could not be verified.");
      return null;
    }
    host.settings.pendingFreeUsageClaims = host.settings.pendingFreeUsageClaims.filter((id) => id !== stableFreeEventId);
    host.settings.freeRepairBatchesUsed = Math.max(0, 3 - accountFree.remaining);
    await host.persistBillingSettings();
    return {
      source: "free",
      commit: async () => ({ kind: "committed" }),
      rollback: async () => void 0
    };
  }
  if (host.settings.purchasedRepairBatches <= 0) await syncBalance(host, requester);
  if (host.settings.purchasedRepairBatches <= 0) {
    host.settings.purchasedRepairBatches = 0;
    await host.persistBillingSettings();
    showNotice("Cairn: today's 3 free repair batches are used. Buy more repair credits in Cairn settings.");
    return null;
  }
  const stableEventId = eventId();
  host.settings.pendingRepairCharges = [...(_c = host.settings.pendingRepairCharges) != null ? _c : [], stableEventId];
  await host.persistBillingSettings();
  let settled = false;
  return {
    source: "purchased",
    commit: async () => {
      if (settled) return { kind: "committed" };
      const result = await spendConstanceCredits(host, 1, requester, stableEventId);
      if (result.kind === "error") return { kind: "pending" };
      settled = true;
      host.settings.pendingRepairCharges = host.settings.pendingRepairCharges.filter((id) => id !== stableEventId);
      if (result.kind === "insufficient") {
        host.settings.purchasedRepairBatches = 0;
        await host.persistBillingSettings();
        return { kind: "insufficient" };
      }
      host.settings.purchasedRepairBatches = result.balance;
      try {
        await host.persistBillingSettings();
      } catch (e) {
        host.settings.pendingRepairCharges = [...host.settings.pendingRepairCharges, stableEventId];
        return { kind: "pending" };
      }
      return { kind: "committed" };
    },
    rollback: async () => {
      if (settled) return;
      host.settings.pendingRepairCharges = host.settings.pendingRepairCharges.filter((id) => id !== stableEventId);
      await host.persistBillingSettings();
    }
  };
}
async function pollCheckout(host, checkoutId, requester = defaultRequester) {
  var _a;
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) return "error";
  const response = await requestWithFreshAccessToken(host, requester, () => ({
    url: `${BASE_URL}/api/v1/billing/checkouts/${encodeURIComponent(checkoutId)}`,
    method: "GET",
    headers: { Authorization: `Bearer ${host.settings.billingAccessToken}` },
    throw: false
  }));
  if (response.status < 200 || response.status >= 300) return "error";
  const data = (_a = response.json) == null ? void 0 : _a.data;
  const status = String((data == null ? void 0 : data.status) || "").toLowerCase();
  if ((data == null ? void 0 : data.settled) === true || ["paid", "completed", "success", "succeeded"].includes(status)) {
    await syncBalance(host, requester);
    return "settled";
  }
  return "pending";
}
async function openCheckout(host, pack, requester = defaultRequester) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  if (!host.settings.billingAccessToken || !host.settings.billingAccountLinked) {
    showNotice("Sign in or create a billing account in Cairn settings before buying credits.");
    return;
  }
  const email = host.settings.billingEmail.trim();
  const planCode = CAIRN_PLAN_CODES[pack];
  const priceId = CAIRN_PRICE_IDS[pack];
  const deviceId = ensureDeviceId(host);
  if (!email || !email.includes("@")) {
    showNotice("Enter a valid billing email in Cairn settings first.");
    return;
  }
  if (!deviceId || !planCode) {
    showNotice("Cairn billing has an invalid pack configuration. No checkout was opened.");
    return;
  }
  const pendingCheckoutKeys = (_a = host.settings.pendingCheckoutKeys) != null ? _a : {};
  const idempotencyKey = pendingCheckoutKeys[pack] || `checkout_${eventId()}`;
  host.settings.pendingCheckoutKeys = { ...pendingCheckoutKeys, [pack]: idempotencyKey };
  await host.persistBillingSettings();
  let response;
  try {
    response = await requestWithFreshAccessToken(host, requester, () => ({
      url: `${BASE_URL}/api/v1/billing/checkout`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${host.settings.billingAccessToken}`, "Idempotency-Key": idempotencyKey },
      body: JSON.stringify({ app_id: CAIRN_APP_ID, plan_code: planCode, installation_id: deviceId, quantity: 1, coupon_code: null }),
      throw: false
    }));
  } catch (error) {
    console.warn("Cairn: authenticated checkout request failed", error);
    showNotice("Cairn checkout could not be reached. Try again; the same checkout request will be reused safely.");
    return;
  }
  const checkoutUrl = (_c = (_b = response.json) == null ? void 0 : _b.data) == null ? void 0 : _c.checkout_url;
  if (response.status >= 200 && response.status < 300 && typeof checkoutUrl === "string" && checkoutUrl) {
    window.open(checkoutUrl, "_blank");
    const checkoutId = (_e = (_d = response.json) == null ? void 0 : _d.data) == null ? void 0 : _e.checkout_id;
    if (checkoutId !== void 0 && checkoutId !== null) (_f = host.pollAfterCheckout) == null ? void 0 : _f.call(host, String(checkoutId));
    const nextKeys = { ...(_g = host.settings.pendingCheckoutKeys) != null ? _g : {} };
    delete nextKeys[pack];
    host.settings.pendingCheckoutKeys = nextKeys;
    await host.persistBillingSettings();
    return;
  }
  if (response.status === 404 || response.status === 405) {
    if (!/^pri_[a-z0-9]+$/i.test(priceId)) {
      showNotice("Cairn billing has no valid legacy fallback price configuration.");
      return;
    }
    const params = new URLSearchParams({ app_id: CAIRN_APP_ID, price_id: priceId, email, external_customer_id: deviceId });
    window.open(`${BASE_URL}/buy?${params.toString()}`, "_blank");
    const nextKeys = { ...(_h = host.settings.pendingCheckoutKeys) != null ? _h : {} };
    delete nextKeys[pack];
    host.settings.pendingCheckoutKeys = nextKeys;
    await host.persistBillingSettings();
    return;
  }
  showNotice("Cairn checkout could not be created. Try again; no new checkout was opened.");
}

// publish/src/main.ts
init_constance_account();

// publish/src/types.ts
var DEFAULT_CHECKS = {
  "broken-wikilink": true,
  "broken-markdown-link": true,
  "broken-embed": true,
  "missing-heading": true,
  "missing-block-id": true,
  "missing-alias": true,
  "duplicate-link": true,
  "empty-stub": true,
  "duplicate-block-id": true,
  "duplicate-heading-id": true,
  "malformed-link": true
};
var DEFAULT_SETTINGS = {
  checks: { ...DEFAULT_CHECKS },
  ignoredFolders: ".obsidian\n.trash",
  ignoredPatterns: "Templates/**\nAttachments/**",
  scanHiddenFiles: false,
  scanNonMarkdownFiles: false,
  emptyStubMaxCharacters: 120,
  emptyStubMaxMeaningfulLines: 3,
  reportFolder: "Cairn Reports",
  lastScanAt: "",
  lastScanFindingCount: 0,
  lastScanHighCount: 0,
  lastScanFileCount: 0,
  lastScanDurationMs: 0,
  lastFileSignatures: {},
  previousFindingCount: 0,
  ignoredFindings: [],
  constanceDeviceId: "",
  billingEmail: "",
  billingAccessToken: "",
  billingRefreshToken: "",
  billingAccountLinked: false,
  freeRepairDay: "",
  freeRepairBatchesUsed: 0,
  purchasedRepairBatches: 0,
  pendingFreeUsageClaims: [],
  pendingRepairCharges: [],
  pendingCheckoutKeys: {}
};

// publish/src/plugin-support.ts
var import_obsidian2 = require("obsidian");
function safeDetail(value) {
  if (value instanceof Error) return value.stack || value.message;
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch (e) {
    return String(value);
  }
}
var DocumentationModal = class extends import_obsidian2.Modal {
  constructor(app, docs) {
    super(app);
    __publicField(this, "docs", docs);
  }
  onOpen() {
    this.titleEl.setText(`${this.docs.name} documentation`);
    this.contentEl.createEl("p", { text: this.docs.summary });
    const addSection = (title, items) => {
      this.contentEl.createEl("h3", { text: title });
      const list = this.contentEl.createEl("ol");
      for (const item of items) list.createEl("li", { text: item });
    };
    addSection("Quick start", this.docs.quickStart);
    addSection("Useful commands", this.docs.commands);
    addSection("Troubleshooting", this.docs.troubleshooting);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PluginSupport = class {
  constructor(plugin, docs) {
    __publicField(this, "plugin", plugin);
    __publicField(this, "docs", docs);
    __publicField(this, "entries", []);
    __publicField(this, "maxEntries", 250);
  }
  start() {
    this.info("plugin.loaded", `version=${this.plugin.manifest.version}`);
    this.plugin.registerDomEvent(window, "error", (event) => {
      this.error("runtime.error", event.error || event.message);
    });
    this.plugin.registerDomEvent(window, "unhandledrejection", (event) => {
      this.error("runtime.unhandled_rejection", event.reason);
    });
    this.plugin.addCommand({
      id: "open-documentation",
      name: "Open documentation",
      callback: () => new DocumentationModal(this.plugin.app, this.docs).open()
    });
    this.plugin.addCommand({
      id: "copy-debug-log",
      name: "Copy debug log",
      callback: () => {
        void this.copyDiagnostics();
      }
    });
    this.plugin.addCommand({
      id: "open-plugin-settings",
      name: "Open plugin settings",
      callback: () => {
        const setting = this.plugin.app.setting;
        setting == null ? void 0 : setting.open();
        setting == null ? void 0 : setting.openTabById(this.plugin.manifest.id);
      }
    });
  }
  info(event, detail) {
    this.record("info", event, detail);
  }
  warn(event, detail) {
    this.record("warn", event, detail);
  }
  error(event, detail) {
    this.record("error", event, detail);
  }
  record(level, event, detail) {
    const entry = { at: (/* @__PURE__ */ new Date()).toISOString(), level, event };
    if (detail !== void 0) entry.detail = safeDetail(detail).slice(0, 4e3);
    this.entries.push(entry);
    if (this.entries.length > this.maxEntries) this.entries.splice(0, this.entries.length - this.maxEntries);
    const method = level === "error" ? console.error : level === "warn" ? console.warn : console.info;
    method.call(console, `[${this.docs.name}] ${event}`, detail != null ? detail : "");
  }
  async copyDiagnostics() {
    const header = [
      `Plugin: ${this.docs.name}`,
      `Plugin ID: ${this.plugin.manifest.id}`,
      `Version: ${this.plugin.manifest.version}`,
      `Captured: ${(/* @__PURE__ */ new Date()).toISOString()}`,
      `User agent: ${navigator.userAgent}`,
      ""
    ];
    try {
      await navigator.clipboard.writeText(header.concat(this.entries.map(
        (entry) => `${entry.at} [${entry.level.toUpperCase()}] ${entry.event}${entry.detail ? ` \u2014 ${entry.detail}` : ""}`
      )).join("\n"));
      new import_obsidian2.Notice(`${this.docs.name}: debug log copied. Secrets and note contents are not included.`);
    } catch (error) {
      this.error("diagnostics.copy_failed", error);
      new import_obsidian2.Notice(`${this.docs.name}: could not copy the debug log.`);
    }
  }
};

// publish/src/main.ts
var VIEW_TYPE_CAIRN = "cairn-vault-linter";
var FINDING_LABELS = {
  "broken-wikilink": "Broken wikilink",
  "broken-markdown-link": "Broken Markdown link",
  "broken-embed": "Broken embed",
  "missing-heading": "Missing heading",
  "missing-block-id": "Missing block ID",
  "missing-alias": "Missing alias",
  "duplicate-link": "Duplicate link",
  "empty-stub": "Empty note stub",
  "duplicate-block-id": "Duplicate block ID",
  "duplicate-heading-id": "Duplicate heading ID",
  "malformed-link": "Malformed link"
};
var SEVERITY_LABELS = { high: "High", medium: "Medium", low: "Low", info: "Info" };
function mergeSettings(data) {
  return {
    ...DEFAULT_SETTINGS,
    ...data,
    checks: { ...DEFAULT_CHECKS, ...(data == null ? void 0 : data.checks) || {} },
    lastFileSignatures: (data == null ? void 0 : data.lastFileSignatures) || {},
    ignoredFindings: (data == null ? void 0 : data.ignoredFindings) || [],
    pendingRepairCharges: (data == null ? void 0 : data.pendingRepairCharges) || []
  };
}
function escapeCsv(value) {
  return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}
function diffPreview(before, after) {
  const beforeLines = before.split(/\r?\n/);
  const afterLines = after.split(/\r?\n/);
  let first = 0;
  while (first < beforeLines.length && first < afterLines.length && beforeLines[first] === afterLines[first]) first++;
  const beforeEnd = Math.min(beforeLines.length, first + 8);
  const afterEnd = Math.min(afterLines.length, first + 8);
  return [
    "Before:",
    ...beforeLines.slice(first, beforeEnd).map((line) => `- ${line}`),
    "After:",
    ...afterLines.slice(first, afterEnd).map((line) => `+ ${line}`)
  ].join("\n");
}
var CairnVaultLinterPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "support");
    __publicField(this, "lastFindings", []);
    __publicField(this, "lastErrors", []);
    __publicField(this, "lastScan", null);
    __publicField(this, "scanAbort", null);
    __publicField(this, "repairApplying", false);
    __publicField(this, "reader");
  }
  async onload() {
    this.support = new PluginSupport(this, { name: "Cairn Vault Linter", summary: "Scan vault health, review findings, and apply only explicitly approved repairs.", quickStart: ["Open the Cairn view.", "Run a scan with the default checks.", "Review findings before applying repairs."], commands: ["Open vault linter", "Scan vault", "Rollback last repair"], troubleshooting: ["Use Copy debug log before reporting a problem.", "Run a fresh scan if files changed after the report was created."] });
    this.support.start();
    this.settings = mergeSettings(await this.loadData());
    await initializeBilling(this);
    this.reader = this.createReader();
    this.registerView(VIEW_TYPE_CAIRN, (leaf) => new CairnView(leaf, this));
    this.addRibbonIcon("checkmark", "Open Cairn Vault Linter", () => void this.openDashboard());
    this.addCommand({ id: "scan-full-vault", name: "Scan full vault", callback: () => void this.runScan() });
    this.addCommand({ id: "scan-current-note", name: "Scan current note", checkCallback: (checking) => this.scanCurrentNote(checking) });
    this.addCommand({ id: "scan-current-folder", name: "Scan current folder", checkCallback: (checking) => this.scanCurrentFolder(checking) });
    this.addCommand({ id: "scan-changed-notes", name: "Scan changed notes (incremental)", callback: () => void this.runScan(void 0, true) });
    this.addCommand({ id: "cancel-scan", name: "Cancel active scan", callback: () => this.cancelScan() });
    this.addCommand({ id: "rollback-last-repair", name: "Roll back last repair batch", callback: () => void this.rollbackLastRepair() });
    this.addSettingTab(new CairnSettingTab(this.app, this));
  }
  onunload() {
    var _a;
    (_a = this.scanAbort) == null ? void 0 : _a.abort();
  }
  async persistBillingSettings() {
    await this.saveData(this.settings);
  }
  pollAfterCheckout(checkoutId) {
    let attempts = 0;
    const poll = () => {
      attempts += 1;
      void pollCheckout(this, checkoutId).then((status) => {
        if (status !== "pending" || attempts >= 8) window.clearInterval(intervalId);
      });
    };
    const intervalId = window.setInterval(poll, 15e3);
    this.registerInterval(intervalId);
    poll();
  }
  createReader() {
    const getFiles = () => this.app.vault.getFiles().map((file) => ({ path: file.path, basename: file.basename, extension: file.extension, mtime: file.stat.mtime, size: file.stat.size }));
    return {
      getFiles,
      read: async (record) => {
        const file = this.app.vault.getAbstractFileByPath(record.path);
        if (!(file instanceof import_obsidian3.TFile)) throw new Error("File is no longer available");
        return this.app.vault.read(file);
      }
    };
  }
  async openDashboard() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_CAIRN)[0];
    const leaf = existing || this.app.workspace.getRightLeaf(false);
    if (!leaf) return;
    await leaf.setViewState({ type: VIEW_TYPE_CAIRN, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async refreshDashboard() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_CAIRN).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof CairnView) view.render();
    });
  }
  scanCurrentNote(checking) {
    const file = this.app.workspace.getActiveFile();
    if (checking) return !!file && file.extension.toLowerCase() === "md";
    if (file) void this.runScan([file.path]);
    return true;
  }
  scanCurrentFolder(checking) {
    const file = this.app.workspace.getActiveFile();
    const folder = file == null ? void 0 : file.parent;
    if (checking) return !!folder;
    if (folder) void this.runScan(this.app.vault.getMarkdownFiles().filter((candidate) => candidate.path === folder.path || candidate.path.startsWith(`${folder.path}/`)).map((candidate) => candidate.path));
    return true;
  }
  async runScan(scopePaths, incremental = false) {
    if (this.scanAbort) {
      new import_obsidian3.Notice("Cairn is already scanning. Use Cancel scan to stop it first.");
      return;
    }
    await this.openDashboard();
    this.scanAbort = new AbortController();
    const view = this.getView();
    view == null ? void 0 : view.setProgress({ phase: "indexing", currentPath: "", scanned: 0, total: 0, findings: 0 });
    try {
      const result = await scanVault(this.reader, this.settings, scopePaths, incremental, this.scanAbort.signal, (progress) => view == null ? void 0 : view.setProgress(progress), this.lastFindings);
      if (result.cancelled) {
        new import_obsidian3.Notice(`Cairn scan cancelled after ${result.filesScanned} file(s).`);
        return;
      }
      this.lastScan = result;
      this.lastErrors = result.errors;
      this.lastFindings = applyIgnoredFindings(result.findings, this.settings.ignoredFindings);
      const counts = findingCounts(this.lastFindings);
      this.settings.previousFindingCount = this.settings.lastScanFindingCount;
      this.settings.lastScanAt = (/* @__PURE__ */ new Date()).toISOString();
      this.settings.lastScanFindingCount = counts.total;
      this.settings.lastScanHighCount = counts.high;
      this.settings.lastScanFileCount = result.filesScanned;
      this.settings.lastScanDurationMs = result.durationMs;
      this.settings.lastFileSignatures = result.signatures;
      await this.saveData(this.settings);
      await this.refreshDashboard();
      new import_obsidian3.Notice(`Cairn found ${counts.total} finding(s) in ${result.filesScanned} file(s).`);
    } catch (error) {
      new import_obsidian3.Notice(`Cairn scan failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      this.scanAbort = null;
      view == null ? void 0 : view.setProgress(null);
    }
  }
  cancelScan() {
    if (!this.scanAbort) {
      new import_obsidian3.Notice("No Cairn scan is active.");
      return;
    }
    this.scanAbort.abort();
  }
  getView() {
    var _a;
    const view = (_a = this.app.workspace.getLeavesOfType(VIEW_TYPE_CAIRN)[0]) == null ? void 0 : _a.view;
    return view instanceof CairnView ? view : void 0;
  }
  async ignoreFinding(finding) {
    new IgnoreModal(this.app, finding, async (reason, scope) => {
      this.settings.ignoredFindings = [...this.settings.ignoredFindings.filter((item) => item.key !== finding.id), { key: scope === "finding" ? finding.id : scope === "source" ? finding.sourcePath : finding.sourcePath.split("/")[0], reason, scope, createdAt: (/* @__PURE__ */ new Date()).toISOString() }];
      this.lastFindings = applyIgnoredFindings(this.lastFindings, this.settings.ignoredFindings);
      await this.saveData(this.settings);
      await this.refreshDashboard();
    }).open();
  }
  async reviewRepairs(findings) {
    const candidates = findings.filter((finding) => finding.repair && !finding.ignored);
    if (!candidates.length) {
      new import_obsidian3.Notice("There are no exact, reviewable repairs in the current results.");
      return;
    }
    const grouped = /* @__PURE__ */ new Map();
    candidates.forEach((finding) => grouped.set(finding.sourcePath, [...grouped.get(finding.sourcePath) || [], finding]));
    const plans = [];
    for (const [path, fileFindings] of grouped) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian3.TFile)) continue;
      const before = await this.app.vault.read(file);
      const proposals = fileFindings.map((finding) => finding.repair);
      const after = applyTextRepairs(before, proposals).after;
      if (after !== before) plans.push({ path, before, after, proposals });
    }
    if (!plans.length) {
      new import_obsidian3.Notice("Cairn found no note changes to apply. Nothing was charged.");
      return;
    }
    new RepairPreviewModal(this.app, plans, (selected) => void this.applyRepairPlans(selected)).open();
  }
  async applyRepairPlans(plans) {
    if (this.repairApplying) {
      new import_obsidian3.Notice("Cairn is already applying a repair batch.");
      return;
    }
    this.repairApplying = true;
    try {
      const readyPlans = [];
      const skipped = [];
      for (const plan of plans) {
        const file = this.app.vault.getAbstractFileByPath(plan.path);
        if (!(file instanceof import_obsidian3.TFile)) {
          skipped.push(plan.path);
          continue;
        }
        const current = await this.app.vault.read(file);
        if (current !== plan.before || current === plan.after) {
          skipped.push(plan.path);
          continue;
        }
        readyPlans.push(plan);
      }
      if (!hasWritableRepairPlans(readyPlans)) {
        new import_obsidian3.Notice(`Cairn repair skipped ${skipped.length} file(s); there were no note changes to apply. Nothing was charged.`);
        return;
      }
      const journal = { batchId: `cairn-${Date.now()}`, createdAt: (/* @__PURE__ */ new Date()).toISOString(), entries: readyPlans.map((plan) => ({ path: plan.path, before: plan.before, after: plan.after })) };
      const restoreJournal = await prepareRepairJournal(this.app.vault.adapter, this.journalPath(), JSON.stringify(journal));
      let reservation;
      try {
        reservation = await reserveRepairBatch(this);
      } catch (error) {
        await restoreJournal();
        throw error;
      }
      if (!reservation) {
        await restoreJournal();
        return;
      }
      const changed = [];
      const failed = [];
      for (const plan of readyPlans) {
        try {
          const file = this.app.vault.getAbstractFileByPath(plan.path);
          if (!(file instanceof import_obsidian3.TFile)) {
            skipped.push(plan.path);
            continue;
          }
          const current = await this.app.vault.read(file);
          if (current !== plan.before) {
            skipped.push(plan.path);
            continue;
          }
          await this.app.vault.modify(file, plan.after);
          changed.push(plan.path);
        } catch (error) {
          failed.push(`${plan.path}: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
      if (!changed.length) {
        await reservation.rollback();
        await restoreJournal();
      } else {
        const billingResult = await reservation.commit();
        if (billingResult.kind === "pending") new import_obsidian3.Notice("Cairn repair applied. Billing is pending and will retry automatically.");
      }
      new import_obsidian3.Notice(`Cairn repair complete: ${changed.length} changed, ${skipped.length} skipped, ${failed.length} failed. Rollback is available.`);
      await this.refreshDashboard();
    } catch (error) {
      new import_obsidian3.Notice(`Cairn repair could not be applied: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      this.repairApplying = false;
    }
  }
  journalPath() {
    return `${this.manifest.dir || `.obsidian/plugins/${this.manifest.id}`}/repair-journal.json`;
  }
  async rollbackLastRepair() {
    try {
      const journal = JSON.parse(await this.app.vault.adapter.read(this.journalPath()));
      const rolledBack = [];
      const skipped = [];
      for (const entry of journal.entries) {
        const file = this.app.vault.getAbstractFileByPath(entry.path);
        if (!(file instanceof import_obsidian3.TFile)) {
          skipped.push(entry.path);
          continue;
        }
        const current = await this.app.vault.read(file);
        if (!canRollback(current, entry.after)) {
          skipped.push(entry.path);
          continue;
        }
        await this.app.vault.modify(file, entry.before);
        rolledBack.push(entry.path);
      }
      new import_obsidian3.Notice(`Cairn rollback: ${rolledBack.length} restored, ${skipped.length} skipped to protect newer edits.`);
      await this.refreshDashboard();
    } catch (error) {
      new import_obsidian3.Notice(`No recoverable Cairn repair batch was found: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  async exportReport(format) {
    if (!this.lastScan) {
      new import_obsidian3.Notice("Run a scan before exporting a report.");
      return;
    }
    const content = format === "markdown" ? this.markdownReport() : format === "csv" ? this.csvReport() : this.jsonReport();
    new ExportPreviewModal(this.app, format, content, async () => {
      const folder = this.settings.reportFolder.trim().replace(/^\/+|\/+$/g, "") || "Cairn Reports";
      if (!this.app.vault.getAbstractFileByPath(folder)) await this.app.vault.createFolder(folder);
      const extension = format === "markdown" ? "md" : format;
      const path = `${folder}/cairn-report-${(/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-")}.${extension}`;
      await this.app.vault.create(path, content);
      new import_obsidian3.Notice(`Cairn report exported to ${path}.`);
    }).open();
  }
  markdownReport() {
    var _a;
    const counts = findingCounts(this.lastFindings);
    const lines = [`# Cairn Vault Linter report`, ``, `- Scanned: ${this.settings.lastScanAt}`, `- Files scanned: ${((_a = this.lastScan) == null ? void 0 : _a.filesScanned) || 0}`, `- Findings: ${counts.total} (${counts.high} high)`, ``];
    const groups = /* @__PURE__ */ new Map();
    this.lastFindings.forEach((finding) => groups.set(finding.sourcePath, [...groups.get(finding.sourcePath) || [], finding]));
    groups.forEach((findings, path) => {
      lines.push(`## ${path}`, "");
      findings.forEach((finding) => lines.push(`- **${SEVERITY_LABELS[finding.severity]} \xB7 ${FINDING_LABELS[finding.type]}** line ${finding.line}: \`${finding.target}\` \u2014 ${finding.explanation}`, `  - Context: ${finding.context || "(none)"}`));
      lines.push("");
    });
    if (this.lastErrors.length) lines.push("## Files that could not be read", "", ...this.lastErrors.map((error) => `- ${error.path}: ${error.message}`));
    return lines.join("\n");
  }
  csvReport() {
    const header = ["id", "type", "severity", "source", "line", "section", "target", "resolved", "ignored", "context", "explanation"];
    return [header, ...this.lastFindings.map((finding) => [finding.id, finding.type, finding.severity, finding.sourcePath, String(finding.line), finding.section, finding.target, String(finding.resolved), String(!!finding.ignored), finding.context, finding.explanation])].map((row) => row.map(escapeCsv).join(",")).join("\n");
  }
  jsonReport() {
    var _a;
    return JSON.stringify({ generatedAt: (/* @__PURE__ */ new Date()).toISOString(), summary: { filesScanned: ((_a = this.lastScan) == null ? void 0 : _a.filesScanned) || 0, ...findingCounts(this.lastFindings) }, findings: this.lastFindings, errors: this.lastErrors }, null, 2);
  }
};
var CairnView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "progress", null);
    __publicField(this, "typeFilter", "all");
    __publicField(this, "severityFilter", "all");
    __publicField(this, "folderFilter", "all");
    __publicField(this, "stateFilter", "unresolved");
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CAIRN;
  }
  getDisplayText() {
    return "Cairn Vault Linter";
  }
  getIcon() {
    return "checkmark";
  }
  onOpen() {
    this.render();
    return Promise.resolve();
  }
  onClose() {
    return Promise.resolve();
  }
  setProgress(progress) {
    this.progress = progress;
    this.render();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("cairn-view");
    const heading = root.createEl("h1", { text: "Cairn Vault Linter" });
    heading.setAttr("tabindex", "-1");
    root.createEl("p", { text: "A local, reviewable health report for links, references, and dangling notes. Scanning never edits vault content." }).addClass("cairn-subtitle");
    const actions = root.createDiv({ cls: "cairn-actions" });
    this.button(actions, "Scan full vault", () => void this.plugin.runScan(), true);
    this.button(actions, "Changed notes", () => void this.plugin.runScan(void 0, true));
    this.button(actions, "Current note", () => this.plugin.scanCurrentNote(false));
    this.button(actions, "Current folder", () => this.plugin.scanCurrentFolder(false));
    this.button(actions, "Cancel", () => this.plugin.cancelScan(), false, !!this.plugin.scanAbort);
    this.button(actions, "Rollback last repair", () => void this.plugin.rollbackLastRepair());
    if (this.progress) {
      const progress = root.createDiv({ cls: "cairn-progress" });
      progress.setAttr("role", "status");
      progress.setAttr("aria-live", "polite");
      progress.createEl("strong", { text: `Scanning ${this.progress.phase}\u2026` });
      progress.createEl("p", { text: `${this.progress.scanned}/${this.progress.total || "?"} files \xB7 ${this.progress.findings} findings${this.progress.currentPath ? ` \xB7 ${this.progress.currentPath}` : ""}` });
      const bar = progress.createEl("progress");
      bar.max = this.progress.total || 1;
      bar.value = Math.min(this.progress.scanned, bar.max);
      bar.setAttr("aria-label", "Cairn scan progress");
    }
    this.renderSummary(root);
    if (this.plugin.lastFindings.length || this.plugin.lastErrors.length) this.renderResults(root);
    else root.createEl("p", { text: "Run a scan to see grouped findings and safe repair options." }).addClass("cairn-empty");
  }
  renderSummary(root) {
    var _a;
    const counts = findingCounts(this.plugin.lastFindings);
    const grid = root.createDiv({ cls: "cairn-summary", attr: { role: "region", "aria-label": "Scan summary" } });
    const trend = this.plugin.settings.lastScanFindingCount - this.plugin.settings.previousFindingCount;
    this.metric(grid, "Findings", String(counts.total), trend ? `${trend > 0 ? "+" : ""}${trend} since previous scan` : "No previous comparison");
    this.metric(grid, "High severity", String(counts.high), "Needs attention first");
    this.metric(grid, "Files scanned", String(((_a = this.plugin.lastScan) == null ? void 0 : _a.filesScanned) || this.plugin.settings.lastScanFileCount || 0), this.plugin.settings.lastScanAt ? new Date(this.plugin.settings.lastScanAt).toLocaleString() : "Not scanned yet");
    this.metric(grid, "Ignored", String(counts.ignored), "Ignored findings remain reviewable");
  }
  renderResults(root) {
    const toolbar = root.createDiv({ cls: "cairn-filters" });
    this.select(toolbar, "Finding type", this.typeFilter, ["all", ...Object.keys(FINDING_LABELS)], (value) => {
      this.typeFilter = value;
      this.render();
    });
    this.select(toolbar, "Severity", this.severityFilter, ["all", "high", "medium", "low", "info"], (value) => {
      this.severityFilter = value;
      this.render();
    });
    const folders = [...new Set(this.plugin.lastFindings.map((finding) => finding.sourcePath.split("/").slice(0, -1).join("/") || "/"))].sort();
    this.select(toolbar, "Folder", this.folderFilter, ["all", ...folders], (value) => {
      this.folderFilter = value;
      this.render();
    });
    this.select(toolbar, "State", this.stateFilter, ["all", "unresolved", "ignored"], (value) => {
      this.stateFilter = value;
      this.render();
    });
    const exportButton = this.button(toolbar, "Export\u2026", () => new ExportChoiceModal(this.app, (format) => void this.plugin.exportReport(format)).open());
    exportButton.setAttr("aria-label", "Export the current Cairn report");
    this.button(toolbar, "Review safe repairs", () => void this.plugin.reviewRepairs(this.filteredFindings()));
    const findings = this.filteredFindings();
    root.createEl("p", { text: `${findings.length} finding(s) shown${this.plugin.lastErrors.length ? ` \xB7 ${this.plugin.lastErrors.length} unreadable file(s)` : ""}` }).addClass("cairn-filter-summary");
    const groups = /* @__PURE__ */ new Map();
    findings.forEach((finding) => groups.set(finding.sourcePath, [...groups.get(finding.sourcePath) || [], finding]));
    groups.forEach((group, path) => {
      const details = root.createEl("details", { cls: "cairn-source-group" });
      details.open = true;
      details.createEl("summary", { text: `${path} (${group.length})` });
      group.forEach((finding) => this.renderFinding(details, finding));
    });
    if (this.plugin.lastErrors.length) {
      const errors = root.createEl("details", { cls: "cairn-errors" });
      errors.createEl("summary", { text: `Unreadable or malformed files (${this.plugin.lastErrors.length})` });
      this.plugin.lastErrors.forEach((error) => errors.createEl("p", { text: `${error.path}: ${error.message}` }));
    }
  }
  filteredFindings() {
    return this.plugin.lastFindings.filter((finding) => (this.typeFilter === "all" || finding.type === this.typeFilter) && (this.severityFilter === "all" || finding.severity === this.severityFilter) && (this.folderFilter === "all" || (finding.sourcePath.split("/").slice(0, -1).join("/") || "/") === this.folderFilter) && (this.stateFilter === "all" || (this.stateFilter === "ignored" ? finding.ignored : !finding.ignored)));
  }
  renderFinding(parent, finding) {
    const card = parent.createDiv({ cls: `cairn-finding cairn-${finding.severity}` });
    const title = card.createEl("h3", { text: `${FINDING_LABELS[finding.type]} \xB7 line ${finding.line}` });
    title.setAttr("tabindex", "0");
    const badge = title.createSpan({ cls: "cairn-badge", text: SEVERITY_LABELS[finding.severity] });
    badge.setAttr("aria-label", `${SEVERITY_LABELS[finding.severity]} severity`);
    card.createEl("p", { text: finding.explanation });
    const meta = card.createEl("p", { cls: "cairn-meta" });
    meta.createEl("code", { text: finding.target || "(no target)" });
    meta.appendText(` \xB7 ${finding.section} \xB7 ${finding.ignored ? `Ignored: ${finding.ignoredReason}` : finding.resolved ? "Resolved target" : "Unresolved"}`);
    if (finding.context) card.createEl("pre", { text: finding.context }).addClass("cairn-context");
    const buttons = card.createDiv({ cls: "cairn-finding-actions" });
    if (finding.repair && !finding.ignored) this.button(buttons, "Preview exact repair", () => void this.plugin.reviewRepairs([finding]), true);
    this.button(buttons, finding.ignored ? "Keep ignored" : "Ignore\u2026", () => void this.plugin.ignoreFinding(finding));
  }
  metric(parent, label, value, hint) {
    const item = parent.createDiv({ cls: "cairn-metric" });
    item.createEl("span", { text: label }).addClass("cairn-metric-label");
    item.createEl("strong", { text: value });
    item.createEl("small", { text: hint });
  }
  select(parent, label, value, options, onChange) {
    const wrapper = parent.createDiv({ cls: "cairn-filter" });
    const id = `cairn-${label.toLowerCase().replace(/\s+/g, "-")}`;
    const labelEl = wrapper.createEl("label", { text: label, attr: { for: id } });
    labelEl.addClass("cairn-filter-label");
    const select = wrapper.createEl("select", { attr: { id } });
    options.forEach((option) => select.createEl("option", { text: option === "all" ? "All" : FINDING_LABELS[option] || SEVERITY_LABELS[option] || option, value: option }));
    select.value = value;
    select.onchange = () => onChange(select.value);
  }
  button(parent, text, callback, primary = false, enabled = true) {
    const button = parent.createEl("button", { text });
    if (primary) button.addClass("mod-cta");
    button.disabled = !enabled;
    button.onclick = callback;
    return button;
  }
};
var IgnoreModal = class extends import_obsidian3.Modal {
  constructor(app, finding, onSave) {
    super(app);
    __publicField(this, "finding", finding);
    __publicField(this, "onSave", onSave);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Ignore finding" });
    contentEl.createEl("p", { text: `${this.finding.sourcePath}:${this.finding.line} \xB7 ${this.finding.explanation}` });
    let reason = "";
    new import_obsidian3.Setting(contentEl).setName("Reason").setDesc("Keep a short local explanation for future reviews.").addText((text) => {
      text.setPlaceholder("Intentional link, generated note, etc.");
      text.onChange((value) => reason = value);
    });
    let scope = "finding";
    new import_obsidian3.Setting(contentEl).setName("Scope").addDropdown((dropdown) => dropdown.addOptions({ finding: "This finding", source: "This source note", folder: "This source folder" }).setValue(scope).onChange((value) => scope = value));
    const actions = contentEl.createDiv({ cls: "cairn-modal-actions" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    const save = actions.createEl("button", { text: "Ignore" });
    save.addClass("mod-cta");
    save.onclick = () => {
      void this.onSave(reason.trim() || "Ignored by user", scope).then(() => this.close());
    };
  }
};
var RepairPreviewModal = class extends import_obsidian3.Modal {
  constructor(app, plans, onApply) {
    super(app);
    __publicField(this, "plans", plans);
    __publicField(this, "onApply", onApply);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Review exact repairs" });
    contentEl.createEl("p", { text: `${this.plans.length} file(s) will change. No note is written until you choose Apply repairs. A recovery journal is created first.` });
    const preview = contentEl.createEl("pre", { text: this.plans.map((plan) => `## ${plan.path}
${diffPreview(plan.before, plan.after)}`).join("\n\n").slice(0, 16e3) });
    preview.setAttr("aria-label", "Before and after repair preview");
    preview.style.maxHeight = "420px";
    preview.style.overflow = "auto";
    const actions = contentEl.createDiv({ cls: "cairn-modal-actions" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    const apply = actions.createEl("button", { text: "Apply repairs" });
    apply.addClass("mod-cta");
    apply.onclick = () => {
      this.close();
      this.onApply(this.plans);
    };
  }
};
var ExportChoiceModal = class extends import_obsidian3.Modal {
  constructor(app, onChoose) {
    super(app);
    __publicField(this, "onChoose", onChoose);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Export Cairn report" });
    contentEl.createEl("p", { text: "Choose a local format. Cairn will show a preview before creating the report file." });
    ["markdown", "csv", "json"].forEach((format) => {
      const button = contentEl.createEl("button", { text: format.toUpperCase() });
      button.onclick = () => {
        this.close();
        this.onChoose(format);
      };
    });
  }
};
var ExportPreviewModal = class extends import_obsidian3.Modal {
  constructor(app, format, report, onApply) {
    super(app);
    __publicField(this, "format", format);
    __publicField(this, "report", report);
    __publicField(this, "onApply", onApply);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `Preview ${this.format.toUpperCase()} export` });
    contentEl.createEl("p", { text: "This creates a new report note in the configured report folder; it does not change existing notes." });
    const pre = contentEl.createEl("pre", { text: this.report.slice(0, 12e3) });
    pre.style.maxHeight = "400px";
    pre.style.overflow = "auto";
    const actions = contentEl.createDiv({ cls: "cairn-modal-actions" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    const apply = actions.createEl("button", { text: "Create report" });
    apply.addClass("mod-cta");
    apply.onclick = () => {
      void this.onApply().then(() => this.close());
    };
  }
};
var CairnSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin", plugin);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Cairn Vault Linter" });
    containerEl.createEl("p", { text: "All checks run locally. Resetting settings does not change vault notes." });
    new import_obsidian3.Setting(containerEl).setName("Billing").setHeading();
    containerEl.createEl("p", { text: "Scanning, previews, exports, ignores, rollback, and local inspection are always free. Applying one approved repair batch uses one credit only when a note actually changes. You get 3 free repair batches per local calendar day." });
    const billingSummary = containerEl.createEl("p");
    const renderBillingSummary = () => {
      const used = Math.min(3, Math.max(0, this.plugin.settings.freeRepairBatchesUsed));
      billingSummary.setText(`Today: ${used}/3 free repair batches used \xB7 Purchased balance: ${Math.max(0, this.plugin.settings.purchasedRepairBatches).toLocaleString()} credits`);
    };
    renderBillingSummary();
    addBillingAccountSettings(containerEl, { state: this.plugin.settings, appId: "cairn-vault-linter", installationId: this.plugin.settings.constanceDeviceId, appVersion: this.plugin.manifest.version, persist: () => this.plugin.persistBillingSettings(), syncBalance: () => syncBalance(this.plugin), refresh: () => this.display() });
    const buySetting = new import_obsidian3.Setting(containerEl).setName("Buy repair credits").setDesc("One credit authorizes one approved repair batch. Checkout opens only after the exact Cairn price is provisioned.");
    buySetting.addButton((button) => button.setButtonText("Buy $1 (100 credits)").onClick(() => void openCheckout(this.plugin, "usd_001")));
    buySetting.addButton((button) => button.setButtonText("Buy $10 (1,000 credits)").setCta().onClick(() => void openCheckout(this.plugin, "usd_010")));
    new import_obsidian3.Setting(containerEl).setName("Refresh balance").setDesc("Sync purchased repair credits for this install.").addButton((button) => button.setButtonText("Refresh balance").onClick(async () => {
      button.setDisabled(true);
      button.setButtonText("Refreshing\u2026");
      await syncBalance(this.plugin);
      renderBillingSummary();
      button.setDisabled(false);
      button.setButtonText("Refresh balance");
    }));
    void syncBalance(this.plugin).then(renderBillingSummary);
    containerEl.createEl("h3", { text: "Checks" });
    Object.keys(DEFAULT_CHECKS).forEach((type) => new import_obsidian3.Setting(containerEl).setName(FINDING_LABELS[type]).addToggle((toggle) => toggle.setValue(this.plugin.settings.checks[type]).onChange(async (value) => {
      this.plugin.settings.checks[type] = value;
      await this.plugin.saveData(this.plugin.settings);
    })));
    new import_obsidian3.Setting(containerEl).setName("Ignored folders").setDesc("One vault-relative folder per line.").addTextArea((text) => text.setValue(this.plugin.settings.ignoredFolders).onChange(async (value) => {
      this.plugin.settings.ignoredFolders = value;
      await this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian3.Setting(containerEl).setName("Ignored file patterns").setDesc("Simple * wildcards, one pattern per line.").addTextArea((text) => text.setValue(this.plugin.settings.ignoredPatterns).onChange(async (value) => {
      this.plugin.settings.ignoredPatterns = value;
      await this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian3.Setting(containerEl).setName("Scan hidden files").addToggle((toggle) => toggle.setValue(this.plugin.settings.scanHiddenFiles).onChange(async (value) => {
      this.plugin.settings.scanHiddenFiles = value;
      await this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian3.Setting(containerEl).setName("Scan non-Markdown files").setDesc("Include local attachments in broken-embed checks; note contents remain Markdown-only.").addToggle((toggle) => toggle.setValue(this.plugin.settings.scanNonMarkdownFiles).onChange(async (value) => {
      this.plugin.settings.scanNonMarkdownFiles = value;
      await this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian3.Setting(containerEl).setName("Nearly empty maximum characters").addText((text) => text.setValue(String(this.plugin.settings.emptyStubMaxCharacters)).onChange(async (value) => {
      const number = Number(value);
      if (Number.isFinite(number) && number >= 0) {
        this.plugin.settings.emptyStubMaxCharacters = number;
        await this.plugin.saveData(this.plugin.settings);
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("Nearly empty maximum meaningful lines").addText((text) => text.setValue(String(this.plugin.settings.emptyStubMaxMeaningfulLines)).onChange(async (value) => {
      const number = Number(value);
      if (Number.isFinite(number) && number >= 0) {
        this.plugin.settings.emptyStubMaxMeaningfulLines = number;
        await this.plugin.saveData(this.plugin.settings);
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("Report folder").setDesc("Vault-relative folder for exported reports.").addText((text) => text.setValue(this.plugin.settings.reportFolder).onChange(async (value) => {
      this.plugin.settings.reportFolder = value;
      await this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian3.Setting(containerEl).setName("Reset Cairn settings").setDesc("Restore default checks and folders; ignored findings are also cleared. Billing identity and balance settings are preserved.").addButton((button) => button.setButtonText("Reset").onClick(async () => {
      const billing = { constanceDeviceId: this.plugin.settings.constanceDeviceId, billingEmail: this.plugin.settings.billingEmail, billingAccessToken: this.plugin.settings.billingAccessToken, billingRefreshToken: this.plugin.settings.billingRefreshToken, billingAccountLinked: this.plugin.settings.billingAccountLinked, freeRepairDay: this.plugin.settings.freeRepairDay, freeRepairBatchesUsed: this.plugin.settings.freeRepairBatchesUsed, purchasedRepairBatches: this.plugin.settings.purchasedRepairBatches, pendingFreeUsageClaims: this.plugin.settings.pendingFreeUsageClaims, pendingRepairCharges: this.plugin.settings.pendingRepairCharges, pendingCheckoutKeys: this.plugin.settings.pendingCheckoutKeys };
      this.plugin.settings = { ...mergeSettings(null), ...billing };
      await this.plugin.saveData(this.plugin.settings);
      this.display();
      new import_obsidian3.Notice("Cairn settings reset.");
    }));
  }
};
